name: Mise à jour helloasso-open-api

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer le script
        env:
          SWAGGER_URL: ${{ secrets.SWAGGER_URL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO_OWNER: helloasso
          GH_REPO_NAME: helloasso-open-api
          GH_BASE_BRANCH: main
        run: node index.js
